name: cinema_pedia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-70.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^9.0.0
  flutter_dotenv: ^5.1.0
  dio: ^5.2.1+1
  flutter_riverpod: ^2.3.6
  card_swiper: ^2.0.4
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
